### ISSUE TITLE
CSS image masks not working

### ISSUE THREAD

**Issue by corey01** [tsayen/dom-to-image#297]
Hi,

The library works great for me, unless there is a CSS image mask on something within the HTML. If there is, this element is completely skipped by the renderer. 

I've looked into the code and can see the mask is still present at the copy stage.

Is there any advice for how to get this to work?

Thanks!

**Comment by ctf0** [comment]
u had any luck with this yet ?

**Comment by alexmarles** [comment]
I am also having issues with the elements that have mask properties. Any idea on how to make it work?

**Comment by ctf0** [comment]
@tsayen any input on this ?

**Comment by istoan** [comment]
2022 here and CSS mask image still doesn't work. Anyone found a fix for this?

**Comment by marcomanenti22** [comment]
Nothing again unfortunately...

**Comment by PimikaMeaw** [comment]
Still nothing :/

**Comment by marcomanenti22** [comment]
I don't know if i solved in right way but here my working mods:

I hope they will be useful to someone  ; )

[dom-to-image.js.txt](https://github.com/tsayen/dom-to-image/files/9634400/dom-to-image.js.txt)
(rename leave .txt obviusly)

**Comment by alexmarles** [comment]
Hey @marcomanenti22 avoid pasting links for people to download unknown files. This could be considered as a security thread, and you have plenty of options to show pieces of code in GitHub. You can put it in a code block inside a comment like this:

```js
(function() {
    // blablabla
```

Or you can also upload the Javascript file as a [Gist](https://gist.github.com/) and then share it here.

Ultimately, if it's a proposal for a solution, you can always fork the repository, do the changes and [create a Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request), so the maintainers can review and add your code to the repository.

Hope it helps!

**Comment by PimikaMeaw** [comment]
> 

It's working, thank you so much ! It's still not capturing the border-image though, but I'll try a few ways I found. Thanks again for sharing!! :)
